version: "3.4"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    environment:
      NGINX_READ_TIMEOUT: 180 # Custom
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx
    depends_on:
      - mysql
      - mongo
    ports:
      - "443:443"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "welcome"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    command: --smallfiles

  cassandra:
    image: cassandra:4.1
    restart: always
    ports:
      - "9042:9042"

volumes:
  vendor_bundle:
    name: vendor_bundle
    external: true
  bootsnap_cache:
    name: bootsnap_cache
    external: true